<div class="row">

    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Devices List</h2>
            </div>
            <div class="card-body">
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('device', array('action'=>'index'));?>">Devices</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Records</h2>
            </div>
            <div class="card-body">
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('record', array('action'=>'index'));?>">Records</a></p>
            </div>
        </div>
    </div>
</div>
